import csv
from pathlib import Path


PROJECT = Path(__file__).resolve().parents[1]

FIELDS = [
    "candidate_id", "candidate_name", "domain", "jurisdiction",
    "incumbent_standard", "origin_or_formalization", "lock_in_period",
    "historical_objective", "historical_constraints", "historical_evidence",
    "technology_change", "other_changes", "modern_decision_variable",
    "outcomes", "datasets", "switching_costs", "network_costs",
    "regulation", "safety", "externalities", "identifiability",
    "tractability", "comparability", "source_quality",
    "negative_control_suitability", "tfsc_relevance",
    "technology_mediated_relevance", "historical_evidence_score",
    "technology_relevance_score", "decision_clarity_score",
    "current_data_score", "identifiability_score",
    "counterfactual_feasibility_score", "transition_cost_feasibility_score",
    "source_quality_score", "comparability_score", "total_score",
    "exclusion_flag", "verification_status", "screening_status",
    "screening_reason",
]

DOMAIN_DEFAULTS = {
    "built_environment": {
        "historical_objective": "Provide reliable building service with simple local controls.",
        "historical_constraints": "Sparse sensing, electromechanical controls, manual commissioning, and limited computation.",
        "other_changes": "Energy prices, comfort expectations, building use, and climate.",
        "switching_costs": "Retrofit hardware, commissioning, controls integration, and training.",
        "network_costs": "Building-management-system and vendor interoperability.",
        "regulation": "Building, energy, accessibility, and fire codes vary by jurisdiction.",
        "safety": "Indoor-air quality, egress, fire protection, and equipment limits must remain binding.",
        "externalities": "Energy demand, emissions, health, and peak-load effects.",
    },
    "transport": {
        "historical_objective": "Move people or vehicles safely using predictable fixed rules.",
        "historical_constraints": "Limited real-time detection, communication, optimization, and traveler information.",
        "other_changes": "Demand patterns, urban form, vehicle mix, emissions, and equity priorities.",
        "switching_costs": "Infrastructure retrofit, control-center integration, enforcement, and user adaptation.",
        "network_costs": "Corridor, fleet, and jurisdiction-wide interoperability.",
        "regulation": "Road, transit, rail, aviation, or maritime rules apply.",
        "safety": "Collision, fail-safe operation, and degraded-mode performance are binding.",
        "externalities": "Congestion, emissions, noise, access, and injury risk.",
    },
    "automotive_interfaces": {
        "historical_objective": "Provide consistent vehicle operation and inspection with mechanical interfaces.",
        "historical_constraints": "Mechanical linkages, analog displays, limited onboard sensing, and no connectivity.",
        "other_changes": "Vehicle electrification, automation, demographics, and distraction concerns.",
        "switching_costs": "Fleet turnover, homologation, repair tooling, and driver retraining.",
        "network_costs": "Cross-manufacturer conventions and service ecosystems.",
        "regulation": "Vehicle safety and type-approval rules apply.",
        "safety": "Human factors, fail-operational behavior, and cybersecurity are binding.",
        "externalities": "Crash risk, emissions, accessibility, and repairability.",
    },
    "work": {
        "historical_objective": "Coordinate labor and production through simple recurring rules.",
        "historical_constraints": "On-site work, manual records, batch production, and weak demand visibility.",
        "other_changes": "Labor law, workforce composition, service work, and worker preferences.",
        "switching_costs": "Collective bargaining, scheduling systems, training, and managerial change.",
        "network_costs": "Team coordination, customer hours, and supply-chain synchronization.",
        "regulation": "Labor, wage, occupational-safety, and sector rules apply.",
        "safety": "Fatigue, staffing adequacy, and machinery hazards may bind.",
        "externalities": "Worker health, commuting, care responsibilities, and service quality.",
    },
    "education": {
        "historical_objective": "Coordinate mass instruction, assessment, and credentialing.",
        "historical_constraints": "Physical classrooms, scarce instructors, paper materials, and manual grading.",
        "other_changes": "Enrollment, pedagogy, special needs, household access, and labor-market demand.",
        "switching_costs": "Timetables, contracts, facilities, curricula, and credential recognition.",
        "network_costs": "Institutional calendars, transferability, and qualification comparability.",
        "regulation": "Education, privacy, accessibility, and accreditation rules apply.",
        "safety": "Safeguarding, screen exposure, and high-stakes decision errors matter.",
        "externalities": "Equity, family schedules, socialization, and labor-market signaling.",
    },
    "healthcare": {
        "historical_objective": "Deliver safe care with periodic observation and standardized workflows.",
        "historical_constraints": "Manual records, intermittent measurement, limited connectivity, and scarce staff.",
        "other_changes": "Population age, disease burden, staffing, treatment options, and privacy expectations.",
        "switching_costs": "Clinical validation, devices, workflow redesign, training, and liability.",
        "network_costs": "Interoperability across clinicians, devices, records, and payers.",
        "regulation": "Medical-device, privacy, reimbursement, and professional rules apply.",
        "safety": "False alarms, missed deterioration, dosing errors, and cybersecurity are binding.",
        "externalities": "Caregiver burden, antimicrobial resistance, access, and public health.",
    },
    "packaging_consumer": {
        "historical_objective": "Enable mass manufacture, handling, identification, and retail coordination.",
        "historical_constraints": "Manual handling, physical shelves, linear scanning, and limited product data.",
        "other_changes": "E-commerce, demographics, waste policy, and consumer behavior.",
        "switching_costs": "Tooling, labels, inventory, retailer systems, and supplier coordination.",
        "network_costs": "Global logistics, retail scanning, compatibility, and installed equipment.",
        "regulation": "Packaging, labeling, food, waste, and consumer-safety rules apply.",
        "safety": "Tamper evidence, child resistance, contamination, and misuse matter.",
        "externalities": "Material use, waste, transport emissions, and accessibility.",
    },
    "paper_digital_legacy": {
        "historical_objective": "Coordinate documents, communication, and human input across fixed media.",
        "historical_constraints": "Printing presses, paper handling, mechanical keyboards, and low-bandwidth systems.",
        "other_changes": "Globalization, accessibility, digital workflows, and device diversity.",
        "switching_costs": "Installed documents, archives, software, user habits, and legal recognition.",
        "network_costs": "Compatibility across users, devices, institutions, and historical records.",
        "regulation": "Records, accessibility, evidence, telecom, and identity rules may apply.",
        "safety": "Authentication, legibility, emergency use, and archival integrity matter.",
        "externalities": "Paper use, exclusion, fraud, and communication errors.",
    },
    "utilities_infrastructure": {
        "historical_objective": "Provide reliable utility service using stable centralized operating rules.",
        "historical_constraints": "Manual metering, weak telemetry, slow control, and limited forecasting.",
        "other_changes": "Decarbonization, distributed resources, climate, demand, and asset age.",
        "switching_costs": "Long-lived assets, customer equipment, control systems, and tariff migration.",
        "network_costs": "System-wide synchronization and interoperability.",
        "regulation": "Utility, environmental, reliability, and rate-setting rules apply.",
        "safety": "Service continuity, pressure, voltage, water quality, and fail-safe operation bind.",
        "externalities": "Emissions, resource depletion, affordability, and resilience.",
    },
    "household_demography": {
        "historical_objective": "Provide mass-market dimensions and defaults for a reference household or body.",
        "historical_constraints": "Limited anthropometric data, fixed production, and weak personalization.",
        "other_changes": "Ageing, body-size distributions, disability inclusion, and household composition.",
        "switching_costs": "Housing stock, furniture, appliance tooling, and replacement cycles.",
        "network_costs": "Compatibility with rooms, products, and supply chains.",
        "regulation": "Housing, accessibility, product, and consumer rules may apply.",
        "safety": "Falls, reach, posture, thermal exposure, and misuse matter.",
        "externalities": "Accessibility, material use, care burden, and housing affordability.",
    },
    "information_scarcity": {
        "historical_objective": "Make robust recurring decisions with delayed or aggregated information.",
        "historical_constraints": "High sensing, communication, storage, and computation costs.",
        "other_changes": "Market volatility, privacy, cyber risk, and organizational complexity.",
        "switching_costs": "Sensors, data integration, model validation, and process redesign.",
        "network_costs": "Shared identifiers, data formats, and multi-party coordination.",
        "regulation": "Privacy, auditability, financial, and sector-specific rules may apply.",
        "safety": "Automation error, model drift, and degraded-mode operation matter.",
        "externalities": "Privacy, discrimination, congestion, waste, and systemic risk.",
    },
    "null_controls": {
        "historical_objective": "Provide durable compatibility and coordination across a large installed base.",
        "historical_constraints": "Physical interoperability and costly multilateral coordination.",
        "other_changes": "Technology changed, but the coordination function may remain dominant.",
        "switching_costs": "System-wide replacement and migration are potentially prohibitive.",
        "network_costs": "Very high installed-base and compatibility effects.",
        "regulation": "International and national standards may apply.",
        "safety": "Loss of interoperability can create material hazards.",
        "externalities": "Trade, access, resilience, and stranded assets.",
    },
}

# name, domain, incumbent, origin lead, technology change, decision variable,
# outcomes, public-data lead, technology mechanism
CANDIDATES = [
    ("Fixed HVAC schedules", "built_environment", "Clock-based HVAC start/stop schedules", "Building controls and energy-code practice", "Occupancy sensing and model-predictive control", "Zone-level HVAC schedule and setpoints", "Energy, peak demand, comfort hours, air quality", "Building Data Genome; EnergyPlus reference buildings", "sensing; computation; adaptive control"),
    ("Constant ventilation rates", "built_environment", "Fixed outdoor-air rates by area or design occupancy", "Ventilation standards and codes", "CO2 and occupancy-based demand-controlled ventilation", "Outdoor-air flow by zone and time", "Energy, CO2 exposure, humidity, comfort", "ASHRAE reference models; public indoor-air datasets", "sensing; adaptive control"),
    ("Scheduled lighting", "built_environment", "Lights operated by fixed schedules or manual switches", "Electrical and building operating practice", "Occupancy and daylight sensors with networked controls", "Lighting level by zone and time", "Electricity, illuminance, occupant acceptance", "DOE reference buildings; public smart-building traces", "sensing; communication; automation"),
    ("Collective elevator dispatch", "built_environment", "Up/down collective elevator control", "Elevator-control engineering practice", "Destination-control and predictive dispatch", "Car assignment and zoning policy", "Wait time, journey time, energy, crowding", "Open elevator traffic benchmarks and simulation", "sensing; computation; adaptive control"),
    ("Periodic fire-system inspection", "built_environment", "Calendar-based inspection and testing", "Fire codes and maintenance standards", "Remote diagnostics and continuously monitored components", "Inspection interval and condition trigger", "Failure detection, downtime, cost, false alerts", "Authority inspection records; device reliability studies", "sensing; communication"),
    ("Uniform thermal setpoints", "built_environment", "Building-wide heating and cooling setpoints", "Comfort guidance and centralized HVAC practice", "Personal comfort systems and localized sensing", "Setpoint distribution and personal control", "Energy, comfort, equity", "ASHRAE comfort databases; public building traces", "sensing; personalization"),
    ("Continuously running escalators", "built_environment", "Continuous operation during opening hours", "Electromechanical reliability practice", "Presence sensing and variable-speed drives", "Stop/start and speed-control policy", "Energy, wait, wear, safety", "Transit-station energy reports; manufacturer curves", "sensing; automation"),
    ("Static facade shading", "built_environment", "Fixed glazing and static shading geometry", "Building-envelope standards", "Electrochromic glazing and automated shades", "Shading state by facade and time", "Cooling, glare, daylight, cost", "EnergyPlus weather and reference models", "sensing; adaptive control"),
    ("Fixed heating curves", "built_environment", "Outdoor-temperature reset with fixed curve", "Hydronic control practice", "Forecast-aware and learning control", "Supply-temperature trajectory", "Energy, comfort, equipment cycling", "Open weather; building-control datasets", "computation; forecasting"),
    ("Parking minimum requirements", "built_environment", "Minimum parking spaces by land use", "Municipal zoning codes", "Real-time occupancy information and shared mobility platforms", "Required parking capacity and pricing", "Access, land use, cruising, spillover", "Municipal codes; parking sensor datasets", "sensing; digital coordination"),

    ("Fixed-time traffic signals", "transport", "Pre-timed signal plans", "Traffic engineering manuals and local signal plans", "Loop/video detection, connected control, and adaptive optimization", "Phase sequence and green split by time", "Delay, queues, stops, emissions, pedestrian wait", "FHWA datasets; open signal and traffic-count data; SUMO", "sensing; communication; adaptive control"),
    ("Fixed speed limits", "transport", "Static posted speed limits", "Road design and traffic law", "Weather, incident, and traffic sensing with variable signs", "Speed limit by segment and time", "Crashes, travel time, flow stability, emissions", "Open crash, weather, and detector data", "sensing; communication; adaptive control"),
    ("Fixed transit timetables", "transport", "Published periodic timetables", "Rail and bus operating standards", "Automatic vehicle location and real-time dispatch", "Departure times and holding policy", "Wait, reliability, transfers, fleet use", "GTFS and GTFS-realtime archives", "sensing; communication; adaptive control"),
    ("Static bus routes", "transport", "Fixed routes and stops", "Municipal transit network planning", "Demand-responsive routing and mobile booking", "Route, stop, and dispatch decisions", "Access, ride time, operating cost, equity", "GTFS; open trip-demand data", "communication; computation; digital coordination"),
    ("Fixed parking prices", "transport", "Uniform or time-block curb prices", "Municipal parking ordinances", "Space occupancy sensors and digital payment", "Price by block and time", "Occupancy, cruising, revenue, access", "SFpark and municipal parking datasets", "sensing; adaptive control"),
    ("Uniform lane widths", "transport", "Fixed design lane widths by road class", "Highway design manuals", "Lane-keeping assistance and automated steering", "Lane width by context and vehicle mix", "Safety, capacity, land use, speed", "Road inventories; crash microdata", "automation; sensing"),
    ("Fixed airport slot plans", "transport", "Seasonal scheduled airport slots", "Airport coordination rules", "Collaborative decision-making and real-time trajectory data", "Slot and gate allocation under disruption", "Delay, cancellations, fuel, fairness", "OpenSky; BTS on-time data", "communication; computation; digital coordination"),
    ("Fixed-block railway signaling", "transport", "Track divided into fixed occupancy blocks", "Railway signaling standards", "Continuous train localization and moving-block control", "Safe separation and train speed profile", "Capacity, delay, energy, safety margin", "Open rail timetables; simulation benchmarks", "sensing; communication; adaptive control"),
    ("Manual toll plazas", "transport", "Barrier toll collection lanes", "Road tolling operations", "Electronic tolling and plate recognition", "Lane allocation and toll collection method", "Delay, emissions, collection cost, privacy", "Toll-agency traffic reports", "sensing; communication; automation"),
    ("Fixed taxi fleet caps", "transport", "Numerical taxi licenses or medallions", "Municipal taxi regulation", "App-based dispatch and platform demand observation", "Fleet cap and geographic/service obligations", "Wait, utilization, congestion, driver income", "Municipal trip records", "communication; digital coordination"),

    ("Mechanical mirror requirements", "automotive_interfaces", "Required physical rear-view mirrors", "Vehicle construction and use standards", "Camera-monitor systems and digital image processing", "Mirror/camera field, placement, and redundancy", "Visibility, drag, detection, reliability", "Regulatory test procedures; crash and field studies", "sensing; computation"),
    ("Fixed headlamp beam patterns", "automotive_interfaces", "Static low/high beam photometric limits", "Vehicle lighting regulations", "Matrix LEDs and adaptive driving beams", "Beam intensity distribution by scene", "Visibility, glare, energy, detection", "Regulatory photometry; road safety studies", "sensing; adaptive control"),
    ("Periodic emissions inspection", "automotive_interfaces", "Calendar-based tailpipe inspection", "Vehicle emissions programs", "Onboard diagnostics and remote emissions sensing", "Inspection trigger and test intensity", "High-emitter detection, cost, emissions", "Remote-sensing programs; inspection records", "sensing; communication"),
    ("Fixed vehicle maintenance intervals", "automotive_interfaces", "Mileage or calendar service schedules", "Manufacturer service schedules", "Onboard condition monitoring and prognostics", "Service timing by component condition", "Failures, cost, downtime, waste", "Public fleet maintenance data; reliability datasets", "sensing; computation"),
    ("Manual tire-pressure checks", "automotive_interfaces", "Driver or service-station pressure checks", "Vehicle maintenance guidance", "Tire-pressure monitoring systems", "Alert threshold and maintenance trigger", "Fuel use, tire failure, false alerts", "NHTSA evaluations; fleet data", "sensing"),
    ("Fixed dashboard warning lamps", "automotive_interfaces", "Standardized tell-tales with binary states", "Vehicle interface regulations", "Contextual digital displays and diagnostics", "Alert modality, priority, and timing", "Comprehension, response, distraction", "Human-factors studies; regulatory symbols", "computation; adaptive interface"),
    ("Standard gear-selector patterns", "automotive_interfaces", "Conventional PRND or manual shift patterns", "Vehicle-control conventions", "Electronic shift-by-wire and configurable interfaces", "Control mapping and feedback", "Selection errors, learnability, accessibility", "Recall data; human-factors experiments", "digital interface"),
    ("Speedometer display conventions", "automotive_interfaces", "Instrument-panel speed display", "Vehicle display regulations", "Head-up displays and context-aware speed assistance", "Display placement, units, and alerts", "Glance time, compliance, errors", "Simulator studies; speed datasets", "sensing; adaptive interface"),
    ("Fixed steering-wheel control layouts", "automotive_interfaces", "Physical control placement by model convention", "Manufacturer and safety guidance", "Software-defined controls and multimodal input", "Function-to-control mapping", "Task time, errors, distraction", "Human-machine-interface studies", "digital reconfiguration"),
    ("Periodic roadworthiness inspection", "automotive_interfaces", "Annual or biennial vehicle inspection", "National vehicle inspection regimes", "Connected diagnostics and continuous fault reporting", "Inspection interval and remote trigger", "Defect detection, burden, fraud, safety", "Inspection and crash records", "sensing; communication"),

    ("Eight-hour shifts", "work", "Fixed eight-hour daily shift", "Labor statutes and collective agreements", "Digital scheduling and remote coordination", "Shift length and start time", "Output, fatigue, errors, worker preference", "Time-use surveys; sector staffing records", "communication; computation"),
    ("Five-day workweek", "work", "Five working days and two rest days", "Labor agreements and organizational convention", "Remote work and asynchronous collaboration tools", "Workday allocation across week", "Output, wellbeing, coverage, commuting", "Time-use and workplace trials", "communication; digital coordination"),
    ("Fixed office hours", "work", "Common synchronized attendance window", "Administrative operating practice", "Presence tools, cloud work, and asynchronous workflows", "Required overlap and location schedule", "Coordination, output, access, commute", "Time-use; workplace occupancy and trial data", "communication; digital coordination"),
    ("Fixed break schedules", "work", "Prescribed breaks at uniform times", "Labor rules and production-line practice", "Wearables and workload sensing", "Break timing and duration", "Fatigue, injury, throughput, equity", "Occupational studies; wearable datasets", "sensing; adaptive control"),
    ("Time-clock rounding", "work", "Rounding attendance to fixed minute increments", "Payroll-system limitations and policy", "Exact digital time capture", "Payable-time rounding rule", "Wages, administration, disputes", "Labor decisions; payroll simulations", "digital records"),
    ("Periodic performance reviews", "work", "Annual or semiannual appraisal cycle", "Administrative HR practice", "Continuous work systems and feedback platforms", "Feedback and evaluation frequency", "Goal attainment, bias, burden, retention", "Open workforce surveys; field studies", "communication; digital coordination"),
    ("Calendar preventive maintenance", "work", "Fixed maintenance intervals", "Industrial maintenance manuals", "Condition monitoring and predictive models", "Maintenance trigger and replacement threshold", "Failures, downtime, cost, waste", "NASA C-MAPSS; PHM Society datasets", "sensing; computation"),
    ("Batch quality inspection", "work", "Sample inspection after production batches", "Statistical quality-control practice", "Inline machine vision and process sensing", "Inspection sampling and process-adjustment rule", "Defects, scrap, throughput, false rejects", "Open manufacturing quality datasets", "sensing; automation"),
    ("Paper approval workflows", "work", "Sequential handwritten form approval", "Administrative control practice", "Digital signatures and workflow engines", "Approval routing and authorization rule", "Cycle time, errors, auditability, fraud", "Government process datasets; workflow logs", "communication; automation"),
    ("Fixed staffing templates", "work", "Recurring staffing by weekday and shift", "Workforce planning practice", "Real-time demand forecasting and optimization", "Staff count and skill mix by interval", "Wait, overtime, service, fatigue", "Open call-center and service-demand datasets", "computation; adaptive control"),

    ("Fixed class periods", "education", "Uniform lesson periods in a bell schedule", "Mass-school timetable practice", "Learning platforms and fine-grained progress data", "Period length and subject allocation", "Learning, transitions, attention, staffing", "School timetables; learning-platform datasets", "sensing; computation"),
    ("Age-graded cohorts", "education", "Students grouped primarily by chronological age", "Mass public education administration", "Adaptive learning and mastery tracking", "Grouping and progression rule", "Mastery, equity, social outcomes, staffing", "Longitudinal education datasets", "computation; personalization"),
    ("Seat-time credit hours", "education", "Credits awarded by instructional contact time", "Carnegie unit and accreditation practice", "Online and competency-based assessment", "Credit based on time versus demonstrated mastery", "Completion, mastery, transferability, cost", "IPEDS; competency-program evaluations", "digital assessment"),
    ("Fixed examination duration", "education", "Uniform time limit for all examinees", "Paper examination logistics", "Computerized adaptive testing and accessibility tools", "Item count, routing, and time limit", "Measurement precision, burden, fairness", "Public item-response datasets", "computation; adaptive control"),
    ("Fixed testing windows", "education", "Assessment on common calendar dates", "Administrative testing practice", "Secure digital delivery and automated scoring", "Assessment timing and retest policy", "Validity, disruption, equity, security", "State assessment schedules and results", "communication; automation"),
    ("Printed textbook revision cycles", "education", "Multi-year edition and adoption cycles", "Print production and procurement", "Digital publishing and modular updates", "Update frequency and validation workflow", "Currency, error rates, cost, access", "Open textbook repositories and change logs", "communication; digital distribution"),
    ("Scheduled computer labs", "education", "Access through fixed shared-lab periods", "Scarce school computing hardware", "Low-cost devices and cloud services", "Device allocation and access schedule", "Access, utilization, equity, support cost", "School technology surveys", "communication; cloud computation"),
    ("Lecture attendance requirements", "education", "Physical presence at scheduled lectures", "Campus-based instruction practice", "Recorded, streamed, and interactive online teaching", "Required synchronous attendance proportion", "Learning, engagement, access, cost", "Course-level attendance and outcome studies", "communication; digital delivery"),
    ("Uniform classroom capacity", "education", "Fixed student count per room or class", "Facility and staffing standards", "Hybrid participation and adaptive room allocation", "Physical and remote seat allocation", "Learning, crowding, cost, access", "School facilities and enrollment data", "communication; digital coordination"),
    ("Fixed school start times", "education", "Common early-morning start by school tier", "Transport and institutional coordination", "Routing software and digital coordination", "Start times and bus-route schedule", "Sleep, attendance, transport cost, family burden", "District schedules; time-use and transport data", "computation; coordination"),

    ("Intermittent vital-sign rounds", "healthcare", "Vitals measured at fixed multi-hour intervals", "Ward observation protocols", "Continuous wearable and bedside monitoring", "Measurement and escalation frequency", "Detection delay, alarm burden, workload, outcomes", "MIMIC waveform/clinical data where permitted", "sensing; communication"),
    ("Fixed medication rounds", "healthcare", "Medication delivery at common ward times", "Nursing workflow and pharmacy schedules", "Electronic administration records and smart dispensing", "Dose timing and delivery route", "Timeliness, errors, workload, sleep disruption", "Open medication-administration studies", "communication; automation"),
    ("Finger-stick glucose schedules", "healthcare", "Periodic capillary glucose measurement", "Diabetes management protocols", "Continuous glucose monitoring and automated insulin delivery", "Measurement and insulin-control policy", "Time in range, hypoglycemia, burden, cost", "Open glucose datasets and trial summaries", "sensing; adaptive control"),
    ("Calendar device follow-up", "healthcare", "Fixed in-person check intervals for implanted devices", "Clinical follow-up guidance", "Remote device telemetry", "Follow-up interval and alert trigger", "Detection, visits, workload, safety", "Device registries and remote-monitoring trials", "sensing; communication"),
    ("Uniform appointment slots", "healthcare", "Fixed-duration outpatient appointment templates", "Clinic scheduling practice", "Digital triage and predictive duration models", "Slot length and booking rule", "Wait, overtime, access, clinician load", "Open appointment and no-show datasets", "computation; adaptive scheduling"),
    ("Fixed nurse rounding intervals", "healthcare", "Hourly or two-hourly purposeful rounding", "Hospital nursing protocols", "Bed-exit, call-bell, and deterioration sensors", "Rounding trigger and route", "Falls, response time, workload, privacy", "Open inpatient safety studies", "sensing; adaptive control"),
    ("Paper medication charts", "healthcare", "Handwritten prescribing and administration record", "Paper hospital workflow", "Computerized order entry and decision support", "Order-entry and checking workflow", "Errors, alerts, time, interoperability", "Health-IT evaluations and safety reports", "communication; computation"),
    ("Fixed imaging follow-up intervals", "healthcare", "Calendar surveillance after a finding", "Clinical guidelines", "Risk prediction and image-analysis tools", "Follow-up interval by estimated risk", "Delayed diagnosis, over-testing, burden", "Open imaging cohorts where licensed", "computation; personalization"),
    ("Fixed ambulance posts", "healthcare", "Ambulances wait at predetermined bases", "Emergency medical service deployment practice", "GPS, live demand prediction, and dynamic relocation", "Unit location by time and system state", "Response time, coverage, relocation burden", "Open EMS call datasets", "sensing; computation; adaptive control"),
    ("Periodic hand-hygiene audit", "healthcare", "Manual observation at sampled times", "Infection-control audit practice", "Electronic dispenser and location monitoring", "Audit sampling and feedback frequency", "Compliance, infection proxy, privacy, cost", "Hospital studies and dispenser datasets", "sensing; communication"),

    ("Linear retail barcodes", "packaging_consumer", "UPC/EAN linear identifiers", "GS1 retail identification standards", "Two-dimensional codes and networked product data", "Identifier carrier and data payload", "Scan success, traceability, label space, compatibility", "GS1 specifications and retailer studies", "digital identification"),
    ("Fixed pallet dimensions", "packaging_consumer", "Regional standard pallet footprints", "Logistics and material-handling standards", "Robotic warehouses and flexible handling", "Pallet/container footprint and handling policy", "Cube utilization, damage, compatibility, cost", "Freight statistics and warehouse simulations", "automation"),
    ("Shelf-oriented package sizes", "packaging_consumer", "Packages optimized for retail shelf facings", "Retail merchandising and tooling practice", "E-commerce fulfillment and automated storage", "Package dimensions and unit count", "Material, damage, storage, transport, access", "ISTA studies; carrier package datasets", "automation; digital logistics"),
    ("Fixed blister-pack counts", "packaging_consumer", "Standard tablet counts and cavity layouts", "Pharmaceutical packaging practice", "Smart dispensing and adherence monitoring", "Pack size and dosing feedback", "Adherence, waste, safety, cost", "Medicine utilization and packaging studies", "sensing; digital identification"),
    ("Standard battery form factors", "packaging_consumer", "Disposable cylindrical cell sizes", "IEC/ANSI battery standards", "Rechargeable chemistries and embedded packs", "Cell geometry and replaceability", "Energy density, reuse, safety, compatibility", "Battery specifications and lifecycle data", "materials; digital management"),
    ("Fixed appliance test cycles", "packaging_consumer", "Standard laboratory use cycles for efficiency labels", "Energy-label test standards", "Connected appliances and field telemetry", "Test-cycle profile and rating method", "Field energy, comparability, gaming risk", "Regulatory test data; smart-meter traces", "sensing; communication"),
    ("Static use-by labels", "packaging_consumer", "Calendar date labels", "Food labeling regulation and shelf-life practice", "Time-temperature indicators and cold-chain sensing", "Discard threshold based on date or exposure", "Waste, illness risk, cost", "Food-waste and cold-chain datasets", "sensing"),
    ("Fixed deposit denominations", "packaging_consumer", "Uniform container return deposit", "Bottle-bill statutes", "Digital return identification and account-based incentives", "Deposit by container and behavior", "Return rate, fraud, equity, administration", "Bottle-return program data", "digital identification; adaptive incentives"),
    ("Printed instruction leaflets", "packaging_consumer", "Fixed paper instructions packaged with products", "Consumer-product and medicine labeling", "QR-linked updateable and accessible instructions", "Content medium and update process", "Comprehension, currency, access, privacy", "Recall notices and usability studies", "communication; digital distribution"),
    ("Fixed serving-size declarations", "packaging_consumer", "Standard reference amounts on labels", "Nutrition labeling regulation", "Personalized digital dietary tools", "Reference portion and personalized display", "Comprehension, intake, comparability, equity", "Nutrition surveys and labeling experiments", "computation; personalization"),

    ("Letter versus A4 paper", "paper_digital_legacy", "National paper-size standards", "ISO and national paper standards", "Predominantly digital document exchange and responsive layout", "Physical page size and digital default", "Compatibility, printing waste, readability, migration cost", "Printer and paper market data; ISO specifications", "digital distribution"),
    ("QWERTY keyboard layout", "paper_digital_legacy", "QWERTY-family key arrangement", "Typewriter-era de facto standard", "Touchscreens, predictive text, speech, and remapping", "Input mapping or modality", "Speed, errors, learning, accessibility", "Open typing datasets and controlled studies", "computation; adaptive interface"),
    ("Eighty-column text width", "paper_digital_legacy", "80-character terminal and code convention", "Punch-card and terminal constraints", "High-resolution displays and responsive editors", "Line-length default", "Readability, review errors, screen use", "Open code repositories and experiments", "digital display"),
    ("Fax-based document exchange", "paper_digital_legacy", "Facsimile transmission as accepted workflow", "Telecom and legal-administrative practice", "Secure portals, structured data exchange, and e-signatures", "Exchange channel and data structure", "Time, errors, security, interoperability", "Sector surveys and incident reports", "communication; digital coordination"),
    ("Wet-ink signatures", "paper_digital_legacy", "Handwritten signature on paper original", "Contract and evidentiary practice", "Cryptographic signatures and identity platforms", "Authentication and consent mechanism", "Fraud, friction, access, auditability", "Court records; e-signature studies", "computation; digital identity"),
    ("Fixed manuscript pagination", "paper_digital_legacy", "Page and word constraints designed for print workflows", "Publisher production practice", "Digital submission, XML, and online supplements", "Length and presentation rules", "Review burden, reproducibility, readability", "Journal author guidelines and publication metadata", "digital distribution"),
    ("Twelve-hour clock notation", "paper_digital_legacy", "AM/PM time representation", "Regional civil-time convention", "Digital systems spanning jurisdictions", "Time representation and locale handling", "Scheduling errors, usability, compatibility", "Incident reports and usability studies", "digital coordination"),
    ("Postal addressing formats", "paper_digital_legacy", "Country-specific line-oriented addresses", "Postal sorting standards", "Geocoding, digital maps, and global identifiers", "Address representation and validation", "Delivery success, inclusion, interoperability", "Postal standards; open address datasets", "computation; digital identification"),
    ("Fixed form-field lengths", "paper_digital_legacy", "Legacy database and paper-form character limits", "Mainframe and form-design constraints", "Elastic storage and schema validation", "Permitted identifier/name/address length", "Rejection, truncation, interoperability", "Public digital-service schemas and issue logs", "computation; digital records"),
    ("Fixed telephone numbering plans", "paper_digital_legacy", "National digit lengths and geographic codes", "Telephony switching and regulation", "Internet calling, number portability, and identity layers", "Number allocation and identifier architecture", "Exhaustion, routing, fraud, migration cost", "ITU and regulator numbering data", "communication; digital identity"),

    ("Flat electricity tariffs", "utilities_infrastructure", "Uniform volumetric price within broad periods", "Manual metering and rate regulation", "Smart meters and automated demand response", "Retail price by interval and system state", "Peak load, bills, emissions, volatility, equity", "Open Power System Data; smart-meter trials", "sensing; communication; adaptive control"),
    ("Fixed transformer tap settings", "utilities_infrastructure", "Seasonal or manual distribution-voltage settings", "Distribution engineering practice", "On-load tap changers, smart inverters, and feeder sensing", "Voltage-control setpoint by state", "Voltage violations, losses, hosting capacity", "OpenDSS feeders and public grid datasets", "sensing; adaptive control"),
    ("Constant water pressure targets", "utilities_infrastructure", "Fixed pressure setpoints and pump schedules", "Water utility design practice", "Network pressure sensing and variable-speed pumps", "Pump speed and pressure by demand", "Energy, leakage, pressure compliance, failures", "EPANET benchmark networks and utility demand profiles", "sensing; adaptive control"),
    ("Scheduled meter reading", "utilities_infrastructure", "Monthly or periodic manual meter reads", "Utility billing operations", "Advanced metering infrastructure", "Measurement and billing interval", "Accuracy, cost, detection, privacy", "Smart-meter program evaluations", "sensing; communication"),
    ("Fixed waste-collection routes", "utilities_infrastructure", "Recurring route and pickup calendar", "Municipal sanitation operations", "Bin fill sensors, GPS, and dynamic routing", "Pickup day, route, and vehicle assignment", "Distance, overflow, emissions, service", "Municipal route and fill-level datasets", "sensing; computation"),
    ("Astronomical streetlight schedules", "utilities_infrastructure", "Lights switched by fixed dusk/dawn tables", "Street-lighting operations", "LED dimming, motion sensing, and connected control", "Light level by place and time", "Energy, visibility, ecology, maintenance", "Municipal inventories and energy reports", "sensing; communication; adaptive control"),
    ("Periodic sewer inspection", "utilities_infrastructure", "Calendar or rotation-based inspection", "Asset-management practice", "Robotic inspection, distributed sensors, and risk models", "Inspection timing and segment priority", "Failures, overflow, cost, detection", "Municipal asset and failure records", "sensing; computation"),
    ("Deterministic reserve margins", "utilities_infrastructure", "Fixed percentage generation-capacity margin", "Power-system reliability planning", "Probabilistic forecasting and renewable telemetry", "Reserve requirement by horizon and state", "Reliability, cost, curtailment, emissions", "ENTSO-E/EIA data and adequacy models", "sensing; computation"),
    ("Calendar irrigation schedules", "utilities_infrastructure", "Watering on fixed days or intervals", "Irrigation practice and restrictions", "Soil-moisture sensing, weather forecasts, and automated valves", "Water amount and timing by plot", "Yield, water, energy, runoff", "FAO crop data; open weather; field trials", "sensing; adaptive control"),
    ("Fixed district-heating temperatures", "utilities_infrastructure", "Seasonal supply-temperature curves", "District heating design standards", "Building telemetry, weather forecasts, and network optimization", "Supply temperature and flow by time", "Heat loss, comfort, pump energy, capacity", "Open district-energy datasets and weather", "sensing; computation"),

    ("Kitchen counter height", "household_demography", "Uniform residential worktop height", "Housing and kitchen design conventions", "Low-cost adjustable mechanisms and mass customization", "Height or adjustable range", "Posture, reach, cost, accessibility", "Anthropometric surveys and building standards", "manufacturing flexibility"),
    ("Toilet seat height", "household_demography", "Standard residential fixture height", "Plumbing product and building standards", "Accessible variants and flexible manufacturing", "Height by user population or adjustable design", "Transfers, falls, comfort, cost", "Anthropometric and falls data", "manufacturing flexibility"),
    ("Residential stair geometry", "household_demography", "Fixed rise/run ranges", "Building codes", "Improved sensing, lifts, and adaptable housing systems", "Stair geometry and alternative circulation", "Falls, space, access, cost", "Building codes and injury surveillance", "sensing; assistive technology"),
    ("Standard bed dimensions", "household_demography", "Regional fixed mattress sizes", "Furniture-market conventions", "Flexible manufacturing and compact-home design", "Bed footprint and modularity", "Sleep space, housing use, compatibility, cost", "Housing and anthropometric surveys", "manufacturing flexibility"),
    ("Family-size package defaults", "household_demography", "Pack sizes based on conventional household units", "Retail and production practice", "Demand data and flexible packaging", "Pack size distribution", "Waste, unit cost, convenience, material", "Household expenditure and food-waste surveys", "computation; manufacturing flexibility"),
    ("Residential thermostat guidance", "household_demography", "Uniform recommended setpoints", "Energy-conservation guidance", "Occupancy sensing and personalized control", "Setpoint by occupant and time", "Energy, health, comfort, affordability", "Time-use, health, and smart-thermostat studies", "sensing; personalization"),
    ("Fixed appliance cycle defaults", "household_demography", "Standard default wash or dry cycle", "Appliance design and test practice", "Load sensing and adaptive cycle control", "Water, temperature, and duration by load", "Energy, water, cleaning, fabric wear", "Regulatory test data and field studies", "sensing; adaptive control"),
    ("School furniture dimensions", "household_demography", "Desk/chair sizes assigned by age bands", "Education furniture standards", "Current anthropometry and adjustable furniture", "Dimension range and assignment rule", "Fit, posture, cost, classroom density", "National anthropometric surveys", "sensing; manufacturing flexibility"),
    ("Clothing-size standards", "household_demography", "Discrete regional size codes", "Apparel standards and industry practice", "Body scanning and made-to-measure production", "Size grid and labeling", "Fit, returns, inclusion, production complexity", "Anthropometric surveys and retail returns", "sensing; computation"),
    ("Residential occupancy assumptions", "household_demography", "Design loads based on standard household profiles", "Building energy and utility models", "Smart-meter and occupancy data", "Design profile and diversity factor", "Capacity, energy, comfort, resilience", "Residential energy surveys and load profiles", "sensing; computation"),

    ("Periodic inventory counts", "information_scarcity", "Cycle counts and annual physical inventory", "Accounting and warehouse practice", "RFID, computer vision, and continuous inventory systems", "Count frequency and reconciliation rule", "Stock accuracy, labor, shrinkage, service", "Open retail and warehouse datasets", "sensing; communication"),
    ("Fixed safety-stock formulas", "information_scarcity", "Static reorder buffers from historical averages", "Inventory-control practice", "Streaming demand and supply-chain visibility", "Safety stock by item and time", "Stockouts, holding, waste, resilience", "M5 forecasting; open supply-chain datasets", "communication; computation"),
    ("Fixed reorder points", "information_scarcity", "Static inventory trigger", "Inventory-control practice", "Real-time sales and probabilistic lead-time forecasts", "Reorder threshold and quantity by state", "Service, cost, waste, volatility", "M5 and retail transaction datasets", "sensing; computation"),
    ("Calendar equipment inspection", "information_scarcity", "Inspection after fixed operating time", "Maintenance and safety standards", "Continuous condition monitoring", "Inspection interval and alarm threshold", "Failure, downtime, inspection burden", "NASA and PHM condition datasets", "sensing; computation"),
    ("Decennial census", "information_scarcity", "Population enumeration at long fixed intervals", "National statistical law and administration", "Administrative data integration and digital registers", "Enumeration frequency and update method", "Accuracy, cost, privacy, representation", "National statistics quality reports", "communication; digital records"),
    ("Batch financial settlement", "information_scarcity", "End-of-day or multi-day clearing cycles", "Banking operations and legacy systems", "Real-time gross settlement and distributed messaging", "Settlement timing and liquidity rule", "Liquidity, risk, cost, resilience", "Central-bank payment statistics", "communication; automation"),
    ("Static fraud rules", "information_scarcity", "Fixed thresholds and manually revised rules", "Payment risk-control practice", "Streaming analytics and adaptive models", "Alert and blocking rule by transaction context", "Fraud loss, false positives, bias, latency", "Public fraud datasets", "sensing; computation"),
    ("Periodic credit scoring", "information_scarcity", "Score updated at application or reporting cycles", "Credit-bureau practice", "Open banking and cash-flow analytics", "Update frequency and feature set", "Default prediction, access, bias, privacy", "Public credit datasets and regulatory studies", "communication; computation"),
    ("Static hazard maps", "information_scarcity", "Maps revised on multi-year cycles", "Planning and insurance practice", "Remote sensing, IoT gauges, and rapid modeling", "Hazard zone by current conditions", "Warning, exposure, false alarm, planning stability", "Open satellite, weather, and hazard data", "sensing; computation"),
    ("Climatological schedule rules", "information_scarcity", "Operations based on historical seasonal normals", "Agriculture, energy, and transport planning", "High-resolution forecasts and nowcasting", "Operational trigger by forecast distribution", "Loss, delay, resource use, robustness", "Open weather forecasts and observations", "sensing; computation"),
    ("Static wayfinding signs", "information_scarcity", "Fixed directional signage", "Road and facility standards", "GPS, indoor positioning, and live routing", "Information channel and route recommendation", "Travel time, accessibility, resilience, privacy", "OpenStreetMap and mobility studies", "communication; computation"),
    ("Periodic utility-load forecasts", "information_scarcity", "Daily or seasonal forecast updates", "Utility planning practice", "Streaming smart-meter and weather data", "Forecast update interval and reserve response", "Forecast error, reserve cost, reliability", "Open energy and weather datasets", "sensing; computation"),

    ("ISO shipping-container dimensions", "null_controls", "ISO intermodal container dimensions and corner fittings", "ISO freight-container standards", "Robotics and digital logistics improve handling without removing physical interchange", "Retain or alter container dimensions", "Compatibility, cube utilization, handling cost, stranded assets", "ISO specifications and global freight statistics", "automation; digital coordination"),
    ("Standard railway gauge", "null_controls", "Dominant national or regional track gauge", "Railway infrastructure standards", "Advanced bogies and control do not remove network geometry", "Retain, convert, or dual-gauge network", "Interoperability, capacity, conversion cost, safety", "Infrastructure inventories and traffic statistics", "mechanical adaptation"),
    ("A-series paper proportions", "null_controls", "ISO 216 constant-aspect paper series", "ISO paper-size standard", "Digital documents reduce paper use but preserve scaling convenience", "Retain or change aspect-ratio series", "Scaling, compatibility, paper use, migration", "ISO specifications and printer-market data", "digital distribution"),
    ("Aviation phonetic alphabet", "null_controls", "ICAO spelling alphabet", "International aviation and radio standardization", "Digital datalink supplements but does not eliminate degraded voice channels", "Retain or redesign code words", "Comprehension, error, multilingual robustness, retraining", "ICAO material and communication studies", "communication"),
    ("SI base units", "null_controls", "International System of Units", "International metrology agreements", "Digital measurement increases precision but benefits from common units", "Retain or change unit definitions and dissemination", "Traceability, compatibility, conversion risk", "BIPM publications and calibration data", "sensing; computation"),
    ("Emergency exit pictograms", "null_controls", "Standardized graphical exit signs", "Fire-safety and signage standards", "Digital signage can adapt but static fail-safe symbols remain valuable", "Static versus adaptive sign system", "Recognition, power-loss resilience, compatibility", "Standards and human-factors studies", "digital display"),
    ("Electrical plug and socket systems", "null_controls", "National plug/socket geometries and voltages", "National electrical standards", "Power electronics enable adapters but installed-base and safety constraints persist", "Retain or migrate connector system", "Safety, compatibility, conversion cost, e-waste", "IEC/regulator specifications and market data", "power electronics"),
    ("Fire-hose coupling standards", "null_controls", "Regional standardized hose connections", "Fire-service interoperability standards", "Adapters and logistics software do not remove emergency interchange value", "Retain or harmonize coupling", "Connection success, response, migration cost", "Fire standards and equipment inventories", "digital coordination"),
    ("Maritime distress signal SOS", "null_controls", "Internationally recognized distress signal", "International radiotelegraph convention", "Satellite and digital distress systems supplement legacy channels", "Retain or retire legacy signal", "Recognition, redundancy, training cost", "IMO/ITU rules and incident records", "communication"),
    ("Standard pallet labels", "null_controls", "Globally standardized logistics label fields", "GS1 logistics standards", "Machine vision and RFID supplement rather than negate shared identifiers", "Retain or change identifier schema", "Interoperability, error, migration, traceability", "GS1 specifications and logistics studies", "digital identification"),
]


def build_row(index, item):
    name, domain, incumbent, origin, technology, decision, outcomes, datasets, mechanism = item
    defaults = DOMAIN_DEFAULTS[domain]
    prefix = {
        "built_environment": "BE", "transport": "TR", "automotive_interfaces": "AI",
        "work": "WK", "education": "ED", "healthcare": "HC",
        "packaging_consumer": "PC", "paper_digital_legacy": "PD",
        "utilities_infrastructure": "UI", "household_demography": "HD",
        "information_scarcity": "IS", "null_controls": "NC",
    }[domain]
    domain_index = sum(1 for prior in CANDIDATES[:index] if prior[1] == domain) + 1
    tech_score = 3 if any(x in mechanism for x in ("sensing", "adaptive", "computation", "communication", "automation")) else 2
    control = domain == "null_controls"
    scores = {
        "historical_evidence_score": 1,
        "technology_relevance_score": tech_score,
        "decision_clarity_score": 2,
        "current_data_score": 1,
        "identifiability_score": 1,
        "counterfactual_feasibility_score": 1,
        "transition_cost_feasibility_score": 1,
        "source_quality_score": 0,
        "comparability_score": 1,
    }
    row = {
        "candidate_id": f"{prefix}{domain_index:02d}",
        "candidate_name": name,
        "domain": domain,
        "jurisdiction": "International or jurisdiction-specific; verify before selection",
        "incumbent_standard": incumbent,
        "origin_or_formalization": origin,
        "lock_in_period": "To be established from authoritative historical sources",
        "historical_objective": defaults["historical_objective"],
        "historical_constraints": defaults["historical_constraints"],
        "historical_evidence": "Candidate-level lead only; authoritative history not yet verified",
        "technology_change": technology,
        "other_changes": defaults["other_changes"],
        "modern_decision_variable": decision,
        "outcomes": outcomes,
        "datasets": datasets,
        "switching_costs": defaults["switching_costs"],
        "network_costs": defaults["network_costs"],
        "regulation": defaults["regulation"],
        "safety": defaults["safety"],
        "externalities": defaults["externalities"],
        "identifiability": "Provisional; requires separation of technology from demographic, economic, regulatory, and behavioral change",
        "tractability": "Potentially tractable with public data or an explicitly calibrated open model; not yet verified",
        "comparability": "Comparable at the protocol level; outcome units remain case-specific",
        "source_quality": "No retained candidate-specific source yet",
        "negative_control_suitability": "High" if control else "Possible if the incumbent remains near-optimal",
        "tfsc_relevance": "Technology-governance question concerning persistence under changed constraints",
        "technology_mediated_relevance": mechanism,
        **scores,
        "total_score": sum(scores.values()),
        "exclusion_flag": "",
        "verification_status": "unverified_longlist",
        "screening_status": "longlist",
        "screening_reason": "Plausible candidate retained for evidence-first screening; score excludes effect direction and magnitude",
    }
    return row


rows = [build_row(index, item) for index, item in enumerate(CANDIDATES)]
with (PROJECT / "candidate_registry.csv").open("w", newline="", encoding="utf-8") as fh:
    writer = csv.DictWriter(fh, fieldnames=FIELDS, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)

print(f"Wrote {len(rows)} candidates")
